build/Dockerfile, build/Dockerfile.prow
Signed-off-by: Roke Jung <roke@redhat.com>
=> org name change

.gitignore, cmd/gitopscluster/exec/manager.go, examples/gitopscluster.yaml, examples/managedclusterset.yaml, examples/managedclustersetbinding.yaml, examples/placement.yaml, go.mod, go.sum, hack/test/crds/clusters.open-cluster-management.io_placementdecisions.crd.yaml, hack/test/crds/clusters.open-cluster-management.io_placements.crd.yaml, pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopscluster/gitopscluster_controller_suite_test.go, pkg/controller/gitopscluster/gitopscluster_controller_test.go, pkg/utils/cluster.go
Signed-off-by: Roke Jung <roke@redhat.com>
=> Upgrade Placement API to v1beta1

pkg/utils/cluster_test.go, pkg/utils/eventlog.go, pkg/utils/kubernetes_test.go, pkg/utils/utils_suite_test.go
https://github.com/stolostron/backlog/issues/22704
=> Add unit tests to increase code coverage

pkg/controller/controller_test.go, pkg/utils/eventlog_test.go, pkg/utils/placement_test.go
Signed-off-by: Mike Ng <ming@redhat.com>
=> increase test coverage

.github/workflows/go-postsubmit.yml, .github/workflows/go-presubmit.yml, .github/workflows/go-release.yml, build/Dockerfile, build/Dockerfile.prow, common/scripts/lint_go.sh, go.mod
https://github.com/stolostron/backlog/issues/26283
=> update go to 1.19

pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopscluster/gitopscluster_controller_test.go
When updating the managed cluster secrets in an argocd namespace, the labels, annotations and data from the existing secret is unionized with the new secret data. This will allow for pre-defined labels, annotations and data to persist upon an update.
Issue: https://github.com/stolostron/backlog/issues/26573
=> Union existing argocd secrets with new secrets

.github/workflows/go-presubmit.yml, cmd/propagation/main.go, deploy/controller/operator.yaml, e2e/run_e2e.sh
The CSV will need to be updated to reflect the live and ready check update.
=> do not start the propgation controller until the argo cd application CRD is installed

cmd/propagation/main.go, deploy/controller/operator.yaml
Will need to update CSV after this is merged.
=> conform propgation cmd to the other cmd args

pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopssyncresc/gitopssyncresc_controller.go
https://issues.redhat.com/browse/ACM-4382
=> ACM-4382: Security vulnerabilities

e2e/run_e2e.sh, pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopscluster/gitopscluster_controller_test.go
This propagates labels set on ManagedClusters to the secrets created by the GitOpsCluster controller. The labels can e.g. be used in ArgoCD to select different environments when using Kustomize.
The reconciliation code of the GitOpsCluster controller is changed so secrets are always updated, whether they are blank secrets or not. This allows to propagate changes to the labels of a ManagedCluster after a secret was already created.
Fixes #50
=> feat(GitOpsCluster): Propagate ManagedCluster labels to created secrets

pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller.go
This PR is to fix pagination to only paginate the manifestworks, to completely load all into the `appSetClusterStatusMap` to then generate the finished reports.
=> Paginate manifestworks

cmd/propagation/main.go, e2e/run_e2e.sh, propagation-controller/application/application_status_controller.go, propagation-controller/application/application_status_controller_test.go, propagation-controller/application/suite_test.go
Added code back from https://github.com/open-cluster-management-io/multicloud-integrations/pull/53/files
Only net new code is the integration test for the status controller: `application_status_controller_test.go`
=> Add status controller to sync Application status

pkg/controller/gitopssyncresc/gitopssyncresc_controller.go
https://issues.redhat.com/browse/ACM-5319
=> Catch failures when quering search-api

pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopscluster/gitopscluster_controller_test.go
Signed-off-by: philipwu08 <phwu@redhat.com>
=> Clean-up secrets when cluster secrets failed to create for some clusters

deploy/ocm/install.sh
=> Migrate e2e to use ocm repo

pkg/controller/gitopscluster/gitopscluster_controller.go
* [x ] I have taken backward compatibility into consideration.
Signed-off-by: philipwu08 <phwu@redhat.com>
=> Resolve sonar issues

.codecov.yml, .github/workflows/go-presubmit.yml, Makefile
=> Add sec scan and code cov

pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller.go, pkg/utils/cluster.go
* [ x ] I have taken backward compatibility into consideration.
Signed-off-by: philipwu08 <phwu@redhat.com>
=> Fix mem leaks with gitopscluster controller

common/scripts/gobuild.sh, pkg/apis/apps/v1beta1/gitopscluster_types.go, pkg/controller/gitopscluster/gitopscluster_controller.go
=> Update build parameters

pkg/controller/gitopssyncresc/gitopssyncresc_controller.go, pkg/controller/gitopssyncresc/gitopssyncresc_controller_test.go
Issue: https://issues.redhat.com/browse/ACM-6165
Description: 
- Make single call to search instead of 2 separate calls (one to get the applications and another to get the related resources for each application). Use new _parentUid from search to find the related resources for each application.
- Use the new _missingResources property to include resources that are missing from the related resources
* [ x ] I have taken backward compatibility into consideration.
Signed-off-by: philipwu08 <phwu@redhat.com>
=> Utilize search collector enhancements to build appset report

cmd/gitopscluster/exec/manager.go
* [ x ] I have taken backward compatibility into consideration.
Update the gitopscluster controller to only cache secrets containing the label: 
"apps.open-cluster-management.io/cluster-name,argocd.argoproj.io/secret-type":"cluster"
https://issues.redhat.com/browse/ACM-7367
=> Updating caching of secrets in gitopscluster

examples/managedclusterset.yaml, examples/managedclustersetbinding.yaml
=> Add additional comment for newer releases

build/Dockerfile.rhtap
=> enable Konflux pipeline

deploy/crds/apps.open-cluster-management.io_gitopsclusters.yaml, pkg/apis/apps/v1beta1/gitopscluster_types.go
https://issues.redhat.com/browse/ACM-8973
=> API description update for gitOpsCluster CRD

deploy/crds/apps.open-cluster-management.io_multiclusterapplicationsetreports.yaml, pkg/apis/appsetreport/v1alpha1/appsetreport_types.go
=> Update descriptions for the applicationsetreport CRDs

Makefile, Makefile.prow, gitopsaddon/gitopsaddon_controller_test.go
=> merge gitops addon unit test fix resolved in midstream prow pipeline

pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopscluster/gitopscluster_controller_test.go
- Check for ManagedServiceAccount and create secret in ArgoCD namespace
- Watch for ManagedServiceAccount updates and update the secret accordingly
=> Sync to upstream Short lived token ArgoCD push model

.github/workflows/go-postsubmit.yml, .github/workflows/go-presubmit.yml, pkg/controller/gitopscluster/gitopscluster_controller.go
- Sync managed cluster label fix
=> Sync managed cluster label fix

gitopsaddon/addonTemplates/addonTemplates.yaml, gitopsaddon/charts/openshift-gitops-operator/templates/argocd-aggreate-admin.clusterrole.yaml
https://issues.redhat.com/browse/ACM-18023
=> aggregate argocd admin permission to admin role for Argocd pull model

gitopsaddon/addonTemplates/addonTemplates.yaml
=> add default imagePullSecrets for gitops addon

gitopsaddon/charts/openshift-gitops-dependency/templates/openshift-gitops-argocd-application-controller.clusterrolebinding.yaml, gitopsaddon/gitopsaddon_controller.go
=> force install/upgrade gitops helm chart

pkg/controller/gitopscluster/gitopscluster_controller.go
- Add backup label to ArgoCD secret
=> Add backup label to ArgoCD secret
