open-cluster-management-io/multicloud-integrations

pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopscluster/gitopscluster_controller_test.go
Signed-off-by: Roke Jung <roke@redhat.com>
Fix placement role binding to handle multiple GitOps operator instances.
=> fix placement role binding

pkg/controller/gitopscluster/gitopscluster_controller.go
Signed-off-by: Roke Jung <roke@redhat.com>
- Get ArgoCD instance's application set controller SA name properly
- Fix reconcile retries when reconcile fails to verify the ArgoCD instance namespace
=> fix SA name in placement role binding and reconcile retries

cmd/gitopscluster/exec/manager.go, cmd/gitopscluster/exec/options.go
Following recommended default settings of leaseDuration=137s, renewDeadline=107s, and retryPeriod=26s from https://github.com/openshift/library-go/blob/4b9033d00d37b88393f837a88ff541a56fd13621/pkg/config/leaderelection/leaderelection.go#L84
https://github.com/stolostron/backlog/issues/25245
=> Add default controller leader election setting values

cmd/gitopscluster/exec/manager.go, cmd/gitopscluster/exec/options.go
While writing the [doc issue](https://github.com/stolostron/backlog/issues/25868) for https://github.com/stolostron/backlog/issues/25245 I noticed inconsistent naming of the lease duration flag. This change will keep the flag consistent for all the different parts of the controllers.
=> Change lease-duration to leader-election-lease-duration

.github/workflows/fossa.yml, .github/workflows/go-postsubmit.yml, .github/workflows/go-presubmit.yml, .github/workflows/go-release.yml
Signed-off-by: Mike Ng <ming@redhat.com>
Need to upgrade GitHub action. See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ for more details.
=> Upgrade github action

pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller.go, pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller_test.go
This PR is for only truncating the hosting-appset label and **NOT** the YAML file name.
Addresses:
- https://issues.redhat.com/browse/ACM-4395
=> ACM-4395 Truncate hosting appset label to align with character limit

cmd/multiclusterstatusaggregation/exec/manager.go
This PR replaces the default cached client for the multiclusterStatusAggregation controller with a non-cached client. Addresses potential Out of memory issues with busy environments.
=> Replace aggregation controller client with non-caching client

cmd/gitopscluster/exec/manager.go, cmd/gitopscluster/exec/options.go, cmd/gitopssyncresc/exec/manager.go, cmd/gitopssyncresc/exec/options.go, cmd/multiclusterstatusaggregation/exec/manager.go, cmd/multiclusterstatusaggregation/exec/options.go, cmd/propagation/main.go, deploy/controller/deploy.yaml, deploy/controller/operator.yaml
This PR updates the leader election settings and renames the leader election options from 
``` 
--renew-deadline ==> leader-election-renew-deadline
--retry-period ==> leader-election-retry-period
```
=> Update leader election settings

deploy/controller/role.yaml
Description:
When the operator was run in a kubernetes cluster, it reported an error about missing permissions on applicationsets and multiclusterapplicationsetreports.
Changes:
- added support for applicationsets and multiclusterapplicationsetreports resources in role permissions
=> Added required permissions

cmd/gitopscluster/exec/manager.go, cmd/multiclusterstatusaggregation/exec/manager.go, cmd/propagation/main.go
The non cached client is applied to the following clients in order to avoid them hit OOM killed issue in scale test where 2500 managed clusters are imported.
- gitopscluster controller in push model
- propagation controller in pull model
- aggregation controller in pull model
Note the runtime scheme is required to be declared when the non cached client is created
=> apply non cached client to pull/push model controllers

cmd/multiclusterstatusaggregation/exec/manager.go
This PR adds the Non-Cached client to the manager of the aggregation controller.
=> Add non-cached client to aggregation controller

deploy/crds/apps.open-cluster-management.io_multiclusterapplicationsetreports.yaml, pkg/apis/appsetreport/v1alpha1/appsetreport_types.go, pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller.go, pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller_test.go
This PR modifies the appsetreport CRD by adding a new `app` field to save the app namespaced name for each cluster. Also working on cleaning up some messages and variable names.
=> Save app namespacedname in clusterConditions

pkg/controller/gitopssyncresc/gitopssyncresc_controller.go, pkg/controller/gitopssyncresc/gitopssyncresc_controller_test.go
Hi,
we need a custom cluster domain when creating an URL for Search API.
My changes are only a concept, I would like to make a discussion here about more permanent changes:
1st way: Completely omit the root domain, so use svc.ns.svc only, not sure all clusters have default search root cluster domain inside  /etc/resolv.conf
2nd way: Adding another cli option, but I don't really like adding more direct options to the method input, it would be fine to have the configuration object accessible in the manager directly, instead of this, or are you of a different opinion?
```
// Setup all Controllers
if err := controller.AddGitOpsSyncRescToManager(mgr, options.SyncInterval, options.AppSetResourceDir, options. ClusterRootDomain); err != nil {
klog.Error(err, "")
os.Exit(1)
}
```
=> Adding support for cluster domain root when creating URL

pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller.go
This PR only initializes the map of clusters to map of appsets once, so each subsequent pass doesn't overwrite the existing data.
=> Only initialize map of clusters per appset once

pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller.go
This PR is to set the deleteOptions for cleaning up manifestWorks to delete in the background.
=> Cleanup orphaned manifestWorks in the background

cmd/gitopscluster/exec/manager.go, go.mod, go.sum, pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/utils/placement.go, pkg/utils/placement_test.go
This PR is to detect if the `managedServiceAccount` exists before setting a watch for the resource. Once the resource is detected, the controller will automatically restart.
Addresses issue: https://github.com/stolostron/backlog/issues/27307
=> Detect if ManagedServiceAccount CRD exists before watching

pkg/utils/placement.go, pkg/utils/placement_test.go
Back porting code coverage from midstream because it originally failed to pass the code coverage gate.
https://github.com/stolostron/multicloud-integrations/pull/136
=> Backport TestIsReadyManagedServiceAccount code coverage

pkg/controller/gitopssyncresc/gitopssyncresc_controller.go
this pod is massively logging in one customer site. Since there is no applicationSet used there, customer doesn't care about the message.
=> set up log level to 1 to avoid massively logging

.gitignore, Makefile, pkg/controller/gitopscluster/gitopscluster_controller.go, pkg/controller/gitopscluster/gitopscluster_controller_test.go, pkg/controller/gitopssyncresc/gitopssyncresc_controller.go, pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller_test.go, pkg/utils/cluster.go, propagation-controller/application/application_controller.go
https://issues.redhat.com/browse/ACM-9736
=> gitopsCluster support on non-OCP clussters

pkg/controller/gitopscluster/gitopscluster_controller.go
=> The server url is missed when generating OCP cluster secret

e2e/hub_app/guestbook-app-set.yaml, e2e/run_e2e.sh, propagation-controller/application/application_status_controller.go, propagation-controller/application/helper.go, propagation-controller/application/helper_test.go
- feat: propagation controller now have the ability to propagate the Application operation field.
- Also updated the e2e propagation test to use AppSet progressive sync instead of automated sync.
- Since automated sync is now turned off in e2e test appset, the test will only pass when the operation field is properly propagated which triggers a sync.
=> feat: propagation controller now have the ability to propagate the Application operation field
